server:
    port: 9000
spring:
    cloud:
        gateway:
            routes:
            - id: autores
              uri: http://localhost:8082
              predicates:
              - Path=/autor/**
            - id: libros
              uri: http://localhost:8081
              predicates:
              - Path=/libro/**
